### ISSUE TITLE
Examples use lower camel case while Python should use snake case

### ISSUE THREAD

**Issue by SamyCoenen** [sglvladi/SphinxTutorial#5]

**Comment by sglvladi** [comment]
@SamyCoenen, I suspect you're referring to ``simpleble``. The reason for using camel case in that package is because the package which it extends (i.e. ``bluepy``) used camel case.

Although PEP8 guidelines recommend snake case, there is no strict requirement to say that Python "has" to be in snake case. But more importantly, as ``simpleble`` is not dependent on this project, this issue is not relevant here.
